imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - PHPOrchestraCMSBundle
        - PHPOrchestraFrontBundle
        - PHPOrchestraDisplayBundle
        - PHPOrchestraIndexationBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine_mongodb:
    connections:
        default:
            server: "%php_orchestra_cms.mongodb.server%"
            options: {}
    default_database: "%php_orchestra_cms.mongodb.database%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mandango:
    default_connection: local
    connections:
        local:
            server:   "%php_orchestra_cms.mongodb.server%"
            database: "%php_orchestra_cms.mongodb.database%"

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%

nelmio_solarium:
    endpoints:
        default:
            host: localhost
            port: 8983
            path: /solr
            core: collection1
            timeout: 5
    clients:
        default:
            endpoints: [default]

lexik_translation:
    fallback_locale: "%kernel.default_locale%"
    managed_locales: %php_orchestra_base.languages_availables%
    storage:
        type: mongodb
        object_manager: default

php_orchestra_indexation:
    indexation:
        - solr

# Default configuration for extension with alias: "php_orchestra_model"
php_orchestra_model:
    content:
        class:                'PHPOrchestra\ModelBundle\Document\Content'
        repository:           PHPOrchestra\ModelBundle\Repository\ContentRepository
    content_type:
        class:                'PHPOrchestra\ModelBundle\Document\ContentType'
        repository:           PHPOrchestra\ModelBundle\Repository\ContentTypeRepository
    node:
        class:                'PHPOrchestra\ModelBundle\Document\Node'
        repository:           PHPOrchestra\ModelBundle\Repository\NodeRepository
    site:
        class:                'PHPOrchestra\ModelBundle\Document\Site'
        repository:           PHPOrchestra\ModelBundle\Repository\SiteRepository
    template:
        class:                'PHPOrchestra\ModelBundle\Document\Template'
        repository:           PHPOrchestra\ModelBundle\Repository\TemplateRepository
    field_index:
        class:                'PHPOrchestra\ModelBundle\Document\FieldIndex'
        repository:           PHPOrchestra\ModelBundle\Repository\FieldIndexRepository
    list_index:
        class:                'PHPOrchestra\ModelBundle\Document\ListIndex'
        repository:           PHPOrchestra\ModelBundle\Repository\ListIndexRepository
