php_orchestra_cms:
    resource: "@PHPOrchestraCMSBundle/Resources/config/routing.yml"
    prefix:   /

php_orchestra_backoffice:
    resource: "@PHPOrchestraBackofficeBundle/Controller"
    type: annotation

php_orchestra_backoffice:
    resource: "@PHPOrchestraBackofficeBundle/Controller"
    type: annotation

php_orchestra_display:
    resource: "@PHPOrchestraDisplayBundle/Controller"
    type: annotation

php_orchestra_api:
    resource: "@PHPOrchestraApiBundle/Controller"
    type: annotation
    prefix: /api

php_orchestra_indexation:
    resource: "@PHPOrchestraIndexationBundle/Controller"
    type: annotation

php_orchestra_translation:
    resource: "@PHPOrchestraTranslationBundle/Resources/config/routing.yml"
